{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.gov.hmcts",
    "module": "ccd-sdk-types",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "efsrj6rca5bhfkulp6epzvenae"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.2.1.jar",
          "url": "ccd-sdk-types-0.2.1.jar",
          "size": 27452,
          "sha512": "e462084c0b63ed84549fc7d3e870b5a1628d71136922ba03381e5867f4b09c3ebf16de9acde4d903ff02e7fce5d244cfef9be8e48b595a082b3c9202c6e8434c",
          "sha256": "4a9388805bb6c1f3f0461e3b5d5278dcab48cff0fce9da4b29c1efa1f9b47aa9",
          "sha1": "a499a9c8afa1e362b256e0aee9508acb1843965b",
          "md5": "3455d350120dd94691aaa88eb722f766"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.2.1.jar",
          "url": "ccd-sdk-types-0.2.1.jar",
          "size": 27452,
          "sha512": "e462084c0b63ed84549fc7d3e870b5a1628d71136922ba03381e5867f4b09c3ebf16de9acde4d903ff02e7fce5d244cfef9be8e48b595a082b3c9202c6e8434c",
          "sha256": "4a9388805bb6c1f3f0461e3b5d5278dcab48cff0fce9da4b29c1efa1f9b47aa9",
          "sha1": "a499a9c8afa1e362b256e0aee9508acb1843965b",
          "md5": "3455d350120dd94691aaa88eb722f766"
        }
      ]
    }
  ]
}
