{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-sdk-types",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "iosxnpsorrgtfb6wbctwfjbape"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.1.jar",
          "url": "ccd-sdk-types-0.1.1.jar",
          "size": 27351,
          "sha512": "75183adc7792b73f51a860ef60c140021668e6dcaee81975e4c89eac38523855033e4b794569eb93e37788cd1ef247a6d99690f767b441e9b0bf5d383ea28ce9",
          "sha256": "9be7fa6b3166a705127dbb8194cafedcd206c2367e99eaeeeccde6141c4b3012",
          "sha1": "e71dd888cc60e0a78c85669e86acdc9617880135",
          "md5": "7c7316e37d425c0785821349015ca7b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.1.jar",
          "url": "ccd-sdk-types-0.1.1.jar",
          "size": 27351,
          "sha512": "75183adc7792b73f51a860ef60c140021668e6dcaee81975e4c89eac38523855033e4b794569eb93e37788cd1ef247a6d99690f767b441e9b0bf5d383ea28ce9",
          "sha256": "9be7fa6b3166a705127dbb8194cafedcd206c2367e99eaeeeccde6141c4b3012",
          "sha1": "e71dd888cc60e0a78c85669e86acdc9617880135",
          "md5": "7c7316e37d425c0785821349015ca7b2"
        }
      ]
    }
  ]
}
