{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-gen",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "di5eund63jgh3enqe2zjkshiea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ccd-sdk",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.6.jar",
          "url": "ccd-gen-0.1.6.jar",
          "size": 32294,
          "sha512": "e8d4421000ecba08e3b5ecfc363b6a13e9dc5da8e5d4f2b6ec0413a76fab08f3d84062ca85eea228dbad26b1df0ce50f695da2317092a87b841b44e529486bee",
          "sha256": "7de12cb7b704eeb3a66702df0e5c8c179198cf734c63e674785c188f17d6a1ab",
          "sha1": "c2b7b4049985ccf9b21156f0ff4d9021a568e0b",
          "md5": "862c1a15ccfcf602e58f2ce9d8af830a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ccd-sdk",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.6.jar",
          "url": "ccd-gen-0.1.6.jar",
          "size": 32294,
          "sha512": "e8d4421000ecba08e3b5ecfc363b6a13e9dc5da8e5d4f2b6ec0413a76fab08f3d84062ca85eea228dbad26b1df0ce50f695da2317092a87b841b44e529486bee",
          "sha256": "7de12cb7b704eeb3a66702df0e5c8c179198cf734c63e674785c188f17d6a1ab",
          "sha1": "c2b7b4049985ccf9b21156f0ff4d9021a568e0b",
          "md5": "862c1a15ccfcf602e58f2ce9d8af830a"
        }
      ]
    }
  ]
}
