{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-sdk-types",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "ecjyafx2jbc7te5skweyhw6544"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.8.jar",
          "url": "ccd-sdk-types-0.1.8.jar",
          "size": 28681,
          "sha512": "591b0061e12502f0c8b72fd0f372e7ee39d44f9b185b60ffdcf2cc84fe8f50d6cf6db4a16f79ed12a73ec7beb9643c5feedd08bd53bfb604b5fe4a56dfe3d15a",
          "sha256": "36dbf373251438230fcf64e0719d46e5b8cdc2e6fa5adc4f511e279da4311171",
          "sha1": "930f8d8b717823da8764a7e7178deba2f2221929",
          "md5": "845a2a5a8042e4c84152cc2f60b89d86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.8.jar",
          "url": "ccd-sdk-types-0.1.8.jar",
          "size": 28681,
          "sha512": "591b0061e12502f0c8b72fd0f372e7ee39d44f9b185b60ffdcf2cc84fe8f50d6cf6db4a16f79ed12a73ec7beb9643c5feedd08bd53bfb604b5fe4a56dfe3d15a",
          "sha256": "36dbf373251438230fcf64e0719d46e5b8cdc2e6fa5adc4f511e279da4311171",
          "sha1": "930f8d8b717823da8764a7e7178deba2f2221929",
          "md5": "845a2a5a8042e4c84152cc2f60b89d86"
        }
      ]
    }
  ]
}
