{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-gen",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "3owgz2qfejaa5k77asonscr45a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ccd-sdk",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.0.jar",
          "url": "ccd-gen-0.1.0.jar",
          "size": 32164,
          "sha512": "567064e138b17f167b8c41e10665eda4d8d00d7403fb1b11411bcf1a570c014224f3c7a1a55444f62f3ce73bd514cb741b28c8b706374bc914470098697d9b22",
          "sha256": "698e867c73975972d4ac0e3183e90ea384f75afe86814669ca740e36864f44d8",
          "sha1": "7fe29f031b084370f0cf7e8cb17ac8d0b1b81506",
          "md5": "dccda0c75b6753c9f998ac00c800120e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ccd-sdk",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.0.jar",
          "url": "ccd-gen-0.1.0.jar",
          "size": 32164,
          "sha512": "567064e138b17f167b8c41e10665eda4d8d00d7403fb1b11411bcf1a570c014224f3c7a1a55444f62f3ce73bd514cb741b28c8b706374bc914470098697d9b22",
          "sha256": "698e867c73975972d4ac0e3183e90ea384f75afe86814669ca740e36864f44d8",
          "sha1": "7fe29f031b084370f0cf7e8cb17ac8d0b1b81506",
          "md5": "dccda0c75b6753c9f998ac00c800120e"
        }
      ]
    }
  ]
}
