{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-gen",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "beikd5egwrhajjqigb2h7wlqxe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "uk.gov.hmcts",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.8.jar",
          "url": "ccd-gen-0.1.8.jar",
          "size": 33787,
          "sha512": "b2573e6cb735b1484505cb982b56f9bf8433dcd0731fbf62ba1b89112bad8b49dfc791871751f0f3a4a7ace2e0485017bf6156a835d8de46015e8cb5ad16233f",
          "sha256": "a29f0ecb4dbc7d2054bcbe5ebb01306c18d0a3ff4da860894edfc21f6de7db65",
          "sha1": "ae8cc085c99ac95d260478effd6c7bcc9c8d8614",
          "md5": "d476b950985e185bf37c321f8e3b3983"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "uk.gov.hmcts",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.8.jar",
          "url": "ccd-gen-0.1.8.jar",
          "size": 33787,
          "sha512": "b2573e6cb735b1484505cb982b56f9bf8433dcd0731fbf62ba1b89112bad8b49dfc791871751f0f3a4a7ace2e0485017bf6156a835d8de46015e8cb5ad16233f",
          "sha256": "a29f0ecb4dbc7d2054bcbe5ebb01306c18d0a3ff4da860894edfc21f6de7db65",
          "sha1": "ae8cc085c99ac95d260478effd6c7bcc9c8d8614",
          "md5": "d476b950985e185bf37c321f8e3b3983"
        }
      ]
    }
  ]
}
