{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-gen",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "iosxnpsorrgtfb6wbctwfjbape"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ccd-sdk",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.1.jar",
          "url": "ccd-gen-0.1.1.jar",
          "size": 32417,
          "sha512": "f75de73c12caaff6b6c651b149a1721398087ba9b02b86758bbec989ef186b03588bb611554047c2173adad3431f89f28fb73c1994d158b6e7f1630fd9bbfb94",
          "sha256": "f6e910b3094349f9183c402c25bd0df1877252b0772a66fbf3fb657bff6ec492",
          "sha1": "5122daf65b985168b73278984b4c59ec65ead9d",
          "md5": "be959ebd0d686757baf8e41ecd18cbcd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ccd-sdk",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.1.jar",
          "url": "ccd-gen-0.1.1.jar",
          "size": 32417,
          "sha512": "f75de73c12caaff6b6c651b149a1721398087ba9b02b86758bbec989ef186b03588bb611554047c2173adad3431f89f28fb73c1994d158b6e7f1630fd9bbfb94",
          "sha256": "f6e910b3094349f9183c402c25bd0df1877252b0772a66fbf3fb657bff6ec492",
          "sha1": "5122daf65b985168b73278984b4c59ec65ead9d",
          "md5": "be959ebd0d686757baf8e41ecd18cbcd"
        }
      ]
    }
  ]
}
