{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-sdk-types",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "6gkfwhdydbfjnols7kvdxs7clm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.2.jar",
          "url": "ccd-sdk-types-0.1.2.jar",
          "size": 27551,
          "sha512": "dc8cd48823e761691f9e1da723d09de1e1a2882a1085bbb61df78c6fe65a1e502caf6f44f34a9d196b99d5d5bb72df5e664af0aab4611d27a090e17274303a64",
          "sha256": "16b4f7e98ee6029655d8e507e5890a4b41dd6eff77169e94282321efc5ef2a0b",
          "sha1": "da362b89bdeeb0a353f74465b40c52f3c422836e",
          "md5": "e6c2a36c3d8529f3b741d7d821298397"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.2.jar",
          "url": "ccd-sdk-types-0.1.2.jar",
          "size": 27551,
          "sha512": "dc8cd48823e761691f9e1da723d09de1e1a2882a1085bbb61df78c6fe65a1e502caf6f44f34a9d196b99d5d5bb72df5e664af0aab4611d27a090e17274303a64",
          "sha256": "16b4f7e98ee6029655d8e507e5890a4b41dd6eff77169e94282321efc5ef2a0b",
          "sha1": "da362b89bdeeb0a353f74465b40c52f3c422836e",
          "md5": "e6c2a36c3d8529f3b741d7d821298397"
        }
      ]
    }
  ]
}
