{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.gov.hmcts",
    "module": "ccd-sdk-types",
    "version": "0.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "wm2rinbj5rh67bxfzcl3laky54"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.3.3.jar",
          "url": "ccd-sdk-types-0.3.3.jar",
          "size": 29561,
          "sha512": "c322d11f6a0a1c0dcce6ff17715d5a402250a710b018904f2b482231b1fea48ea31e7120854a121e834fa7cc29af2249402ef6c7658272f543f1cfe989332acf",
          "sha256": "2835f76e4978d540ff818270a56ab0ea1eefa13557687a0825ec3a3b26d89c77",
          "sha1": "58c7e810ff21aa3a970d65b817d4d30e32921fd0",
          "md5": "4abdbd97578622a701b4113081799cec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.3.3.jar",
          "url": "ccd-sdk-types-0.3.3.jar",
          "size": 29561,
          "sha512": "c322d11f6a0a1c0dcce6ff17715d5a402250a710b018904f2b482231b1fea48ea31e7120854a121e834fa7cc29af2249402ef6c7658272f543f1cfe989332acf",
          "sha256": "2835f76e4978d540ff818270a56ab0ea1eefa13557687a0825ec3a3b26d89c77",
          "sha1": "58c7e810ff21aa3a970d65b817d4d30e32921fd0",
          "md5": "4abdbd97578622a701b4113081799cec"
        }
      ]
    }
  ]
}
