{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-gen",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "7rdjfwwa7jffvfdgmdtrjbv5di"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "uk.gov.hmcts",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.3.0.jar",
          "url": "ccd-gen-0.3.0.jar",
          "size": 37301,
          "sha512": "25316b9b0c217dcfb764cac184664b1a91e0a3532675313838eda59ee9445c9514786bcd744f1f34c0da823c9293a974e4930baafdbc5e731bbb7dfaeb8c43fa",
          "sha256": "944b7be5c9d04a544226b6e0d5d1c089fe5ced6e7ffba33c26db59516bdd9b6c",
          "sha1": "eb1073bb1167399e3297773279da912d17b70f09",
          "md5": "50b6419b8879aee8f62903e3e72b0be5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "uk.gov.hmcts",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.3.0.jar",
          "url": "ccd-gen-0.3.0.jar",
          "size": 37301,
          "sha512": "25316b9b0c217dcfb764cac184664b1a91e0a3532675313838eda59ee9445c9514786bcd744f1f34c0da823c9293a974e4930baafdbc5e731bbb7dfaeb8c43fa",
          "sha256": "944b7be5c9d04a544226b6e0d5d1c089fe5ced6e7ffba33c26db59516bdd9b6c",
          "sha1": "eb1073bb1167399e3297773279da912d17b70f09",
          "md5": "50b6419b8879aee8f62903e3e72b0be5"
        }
      ]
    }
  ]
}
