{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-gen",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qy5dszqagvdcnndjqdrvyakuri"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "uk.gov.hmcts",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.9.jar",
          "url": "ccd-gen-0.1.9.jar",
          "size": 36086,
          "sha512": "6ab28167891981ee9a01bb0e22411363e91866bf39dc9d257559a695b436b9c82d299e42e22a62d7028c73f7cbb875d767635d7d8743abaa3069e335b9132825",
          "sha256": "848131192e0656e43756e347d090464a16ca3ffb20f0718d8ea0612d36582866",
          "sha1": "c94b2065fff47e7cfdfeb4106fea7459fe614ec1",
          "md5": "c44ec57455b724a2815f5d46be5d1161"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "uk.gov.hmcts",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.9.jar",
          "url": "ccd-gen-0.1.9.jar",
          "size": 36086,
          "sha512": "6ab28167891981ee9a01bb0e22411363e91866bf39dc9d257559a695b436b9c82d299e42e22a62d7028c73f7cbb875d767635d7d8743abaa3069e335b9132825",
          "sha256": "848131192e0656e43756e347d090464a16ca3ffb20f0718d8ea0612d36582866",
          "sha1": "c94b2065fff47e7cfdfeb4106fea7459fe614ec1",
          "md5": "c44ec57455b724a2815f5d46be5d1161"
        }
      ]
    }
  ]
}
