{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-gen",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "zygmjd5uwbhyjf37dtn4nn5xlq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ccd-sdk",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.3.jar",
          "url": "ccd-gen-0.1.3.jar",
          "size": 32128,
          "sha512": "ff3140b0870a62d0dd136e466d3b1ce2e81870c8a4c7251dc1043a886855d5978adfac5e68bb4c386aa7c51a5369f21b4569089294dec25f20e79d4db9d8116b",
          "sha256": "c33a25583953cd049c977e2bb4fc0e80d0bf726837fd6057279d4192e2c1dfa",
          "sha1": "c6df3c900fbc03c047a3d8bee1acf01fd2f005b9",
          "md5": "11ce7edd9958c6692e7ce9a8857d8398"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ccd-sdk",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.3.jar",
          "url": "ccd-gen-0.1.3.jar",
          "size": 32128,
          "sha512": "ff3140b0870a62d0dd136e466d3b1ce2e81870c8a4c7251dc1043a886855d5978adfac5e68bb4c386aa7c51a5369f21b4569089294dec25f20e79d4db9d8116b",
          "sha256": "c33a25583953cd049c977e2bb4fc0e80d0bf726837fd6057279d4192e2c1dfa",
          "sha1": "c6df3c900fbc03c047a3d8bee1acf01fd2f005b9",
          "md5": "11ce7edd9958c6692e7ce9a8857d8398"
        }
      ]
    }
  ]
}
