{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-sdk-types",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "di5eund63jgh3enqe2zjkshiea"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.6.jar",
          "url": "ccd-sdk-types-0.1.6.jar",
          "size": 27653,
          "sha512": "3018e0d3b77d5dfbd4bbbfa34fae548da028cad1eefba46e735b5e5dbe70ef276b708dcfaebe8ad40c5bf54317bd95b7f80448a775902a36da3329d5e60ce222",
          "sha256": "9af7c9ae155dc0e21d4565877cc4271bd3f7a6d3bdcc7ccbb133700eeae6576",
          "sha1": "ce3d587cdb57b239b1bc0b5067df074cbba00636",
          "md5": "50fbef62a476b524ef7889cc814a3050"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.6.jar",
          "url": "ccd-sdk-types-0.1.6.jar",
          "size": 27653,
          "sha512": "3018e0d3b77d5dfbd4bbbfa34fae548da028cad1eefba46e735b5e5dbe70ef276b708dcfaebe8ad40c5bf54317bd95b7f80448a775902a36da3329d5e60ce222",
          "sha256": "9af7c9ae155dc0e21d4565877cc4271bd3f7a6d3bdcc7ccbb133700eeae6576",
          "sha1": "ce3d587cdb57b239b1bc0b5067df074cbba00636",
          "md5": "50fbef62a476b524ef7889cc814a3050"
        }
      ]
    }
  ]
}
