{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-gen",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "tgrd34ktwfb7vpuu44niieassy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "uk.gov.hmcts",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.3.1.jar",
          "url": "ccd-gen-0.3.1.jar",
          "size": 37449,
          "sha512": "18e353e4e6291531d16184cbb6da5b08c3817591ecd81fc68a9130678d5bda1ac8bdf4fa0bd4984d0d00f7e103ae36d5db6a0a77ea2ec5d12e1c511ca4ca0e8b",
          "sha256": "572bf1634c5fe6dbc4df41c75a4eebe6ddd278cb4dbbd47f7e7015c46fa5d437",
          "sha1": "2c60e8455e21c5723c48beb1f22b185ed785ad0f",
          "md5": "815896e8eee0198a0e66db3430d4f4be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "uk.gov.hmcts",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.3.1.jar",
          "url": "ccd-gen-0.3.1.jar",
          "size": 37449,
          "sha512": "18e353e4e6291531d16184cbb6da5b08c3817591ecd81fc68a9130678d5bda1ac8bdf4fa0bd4984d0d00f7e103ae36d5db6a0a77ea2ec5d12e1c511ca4ca0e8b",
          "sha256": "572bf1634c5fe6dbc4df41c75a4eebe6ddd278cb4dbbd47f7e7015c46fa5d437",
          "sha1": "2c60e8455e21c5723c48beb1f22b185ed785ad0f",
          "md5": "815896e8eee0198a0e66db3430d4f4be"
        }
      ]
    }
  ]
}
