{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.gov.hmcts",
    "module": "ccd-sdk-types",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "tgrd34ktwfb7vpuu44niieassy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.3.1.jar",
          "url": "ccd-sdk-types-0.3.1.jar",
          "size": 29583,
          "sha512": "10af898538306d8264ec6741a92929bec8b3b0109b34d945845ce8b8c71b34fd7f30a7aa41345cdddf67cc2f1f81a7b0e31b91d622171c0dbab5fcf0342abe68",
          "sha256": "448f4146c24f90648b21967fe80935ba88e7f293eb5e0462f2ab56aa0543fc99",
          "sha1": "57dd95ae667bddb2879f2cf59ffa54f649416046",
          "md5": "4eca53d55e69787563fa951519e638bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.3.1.jar",
          "url": "ccd-sdk-types-0.3.1.jar",
          "size": 29583,
          "sha512": "10af898538306d8264ec6741a92929bec8b3b0109b34d945845ce8b8c71b34fd7f30a7aa41345cdddf67cc2f1f81a7b0e31b91d622171c0dbab5fcf0342abe68",
          "sha256": "448f4146c24f90648b21967fe80935ba88e7f293eb5e0462f2ab56aa0543fc99",
          "sha1": "57dd95ae667bddb2879f2cf59ffa54f649416046",
          "md5": "4eca53d55e69787563fa951519e638bf"
        }
      ]
    }
  ]
}
