{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-gen",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "rhtea3jbfnal7kdxfghjqvbssa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ccd-sdk",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.5.jar",
          "url": "ccd-gen-0.1.5.jar",
          "size": 32294,
          "sha512": "bffab107b277e140d8d5907305f8f9c861b3f9b0fe0336a2d82a887a9710bd801040190aec533101dd333dd5401645b61d2bce856b59523b306e38b7ffdc3b6c",
          "sha256": "30e92eaf24330c90b22154d5d15317d0fdeedd9beb4746476cf85b2f63633d5e",
          "sha1": "46c3ed637f1151d395faf7f44a0d17d14e625fb2",
          "md5": "f976e24bea08baf112f1ce0107ea87c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "ccd-sdk",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.1.5.jar",
          "url": "ccd-gen-0.1.5.jar",
          "size": 32294,
          "sha512": "bffab107b277e140d8d5907305f8f9c861b3f9b0fe0336a2d82a887a9710bd801040190aec533101dd333dd5401645b61d2bce856b59523b306e38b7ffdc3b6c",
          "sha256": "30e92eaf24330c90b22154d5d15317d0fdeedd9beb4746476cf85b2f63633d5e",
          "sha1": "46c3ed637f1151d395faf7f44a0d17d14e625fb2",
          "md5": "f976e24bea08baf112f1ce0107ea87c1"
        }
      ]
    }
  ]
}
