{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-gen",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "asgdmgjmunay5jwc7u2epemnqq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "uk.gov.hmcts",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.3.2.jar",
          "url": "ccd-gen-0.3.2.jar",
          "size": 37449,
          "sha512": "aab27357c9eb9b4427e17798be01a635f1cf48347e36859801f30c28107a85443eccb241e1eed1b905c3f64c4b74da7a31c33399704e80e9b62efc19a040ed66",
          "sha256": "7946bd8e200e18d576a3dc442e83e7540246d7677226d2239dd32de55fe17e60",
          "sha1": "2224ef460bfee215c420ecff11949404049ac4d9",
          "md5": "51dace30934fd650276371e2bf0ea211"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.objenesis",
          "module": "objenesis",
          "version": {
            "requires": "3.1"
          }
        },
        {
          "group": "cglib",
          "module": "cglib",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.9.11"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.8"
          }
        },
        {
          "group": "uk.gov.hmcts",
          "module": "ccd-sdk-types",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-gen-0.3.2.jar",
          "url": "ccd-gen-0.3.2.jar",
          "size": 37449,
          "sha512": "aab27357c9eb9b4427e17798be01a635f1cf48347e36859801f30c28107a85443eccb241e1eed1b905c3f64c4b74da7a31c33399704e80e9b62efc19a040ed66",
          "sha256": "7946bd8e200e18d576a3dc442e83e7540246d7677226d2239dd32de55fe17e60",
          "sha1": "2224ef460bfee215c420ecff11949404049ac4d9",
          "md5": "51dace30934fd650276371e2bf0ea211"
        }
      ]
    }
  ]
}
