{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.gov.hmcts",
    "module": "ccd-sdk-types",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "v32ftzc3gfayvh2eifucwmf6vu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.9.jar",
          "url": "ccd-sdk-types-0.1.9.jar",
          "size": 28681,
          "sha512": "5aba776d9fac5aaebe77d6f12a2b93b71b204defd386aab76dc216ab5c800f0185324004b0fe35206bd2cead2dd8bd6c1d0a1bce6797a9f4518c08607e9509c8",
          "sha256": "2af93ebd802770b8ea32321081845b72e62784d28763094bd927a3c1729daf56",
          "sha1": "f90e340b2e721dc6e7747d4e302f8c43b48135d5",
          "md5": "35b222902a094bc43a8b27e12b3a6d6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.9.jar",
          "url": "ccd-sdk-types-0.1.9.jar",
          "size": 28681,
          "sha512": "5aba776d9fac5aaebe77d6f12a2b93b71b204defd386aab76dc216ab5c800f0185324004b0fe35206bd2cead2dd8bd6c1d0a1bce6797a9f4518c08607e9509c8",
          "sha256": "2af93ebd802770b8ea32321081845b72e62784d28763094bd927a3c1729daf56",
          "sha1": "f90e340b2e721dc6e7747d4e302f8c43b48135d5",
          "md5": "35b222902a094bc43a8b27e12b3a6d6d"
        }
      ]
    }
  ]
}
