{
  "formatVersion": "1.1",
  "component": {
    "group": "uk.gov.hmcts",
    "module": "ccd-sdk-types",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "qy5dszqagvdcnndjqdrvyakuri"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.9.jar",
          "url": "ccd-sdk-types-0.1.9.jar",
          "size": 27452,
          "sha512": "67e99f5dd27a4be03a3c55421051c23c3f2ec6d116fcbcb6dcdc185668f86d8fbff1e736afa2053a2efe2695a295aab4976cad8673e46d90e76be1be9238749e",
          "sha256": "1ee20db3d651622041c60b630639cb9d7e783465d1d68d52536a3875a1a8e141",
          "sha1": "c0c791e8a70e460dcd576ec3bf0325231411f754",
          "md5": "4a05c8b8938b97b5dac70e426a6ceb33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.9.jar",
          "url": "ccd-sdk-types-0.1.9.jar",
          "size": 27452,
          "sha512": "67e99f5dd27a4be03a3c55421051c23c3f2ec6d116fcbcb6dcdc185668f86d8fbff1e736afa2053a2efe2695a295aab4976cad8673e46d90e76be1be9238749e",
          "sha256": "1ee20db3d651622041c60b630639cb9d7e783465d1d68d52536a3875a1a8e141",
          "sha1": "c0c791e8a70e460dcd576ec3bf0325231411f754",
          "md5": "4a05c8b8938b97b5dac70e426a6ceb33"
        }
      ]
    }
  ]
}
