{
  "formatVersion": "1.1",
  "component": {
    "group": "ccd-sdk",
    "module": "ccd-sdk-types",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "wq2gmbqs2zgkpejleasy3nu3ym"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.7.jar",
          "url": "ccd-sdk-types-0.1.7.jar",
          "size": 27653,
          "sha512": "b3ba7e1045afa69889a9978c37673ea8deee7b7c68e298780b778d6fdd6769d40235f2934839035b813502e7bd4f3d1176d7686fa78d0fe37b12e9f4d9076eb5",
          "sha256": "2ae7ac5af52483769693e0160411b98306fc55ae56ec1ef07909b66963e43883",
          "sha1": "8d38020d88c2e888bec9f69d4836c3907a145b9b",
          "md5": "f01c66fc396d22dcf8470ab3378a7294"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          }
        },
        {
          "group": "de.cronn",
          "module": "reflection-util",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-sdk-types-0.1.7.jar",
          "url": "ccd-sdk-types-0.1.7.jar",
          "size": 27653,
          "sha512": "b3ba7e1045afa69889a9978c37673ea8deee7b7c68e298780b778d6fdd6769d40235f2934839035b813502e7bd4f3d1176d7686fa78d0fe37b12e9f4d9076eb5",
          "sha256": "2ae7ac5af52483769693e0160411b98306fc55ae56ec1ef07909b66963e43883",
          "sha1": "8d38020d88c2e888bec9f69d4836c3907a145b9b",
          "md5": "f01c66fc396d22dcf8470ab3378a7294"
        }
      ]
    }
  ]
}
